name=mk-nds-adt
authors=Carsten Rohe, Landesnetzwerk Informatik Niedersachsen
url=https://github.com/karlgerd/processing-mk-nds-adt
categories=Data
sentence=ADT-Klassen für den Informatikunterricht in Niedersachsen.
paragraph=Diese Bibliothek stellt BinTree, DynArray, Queue und Stack gemäß den ergänzenden Hinweisen des Niedersächsischen Kultusministeriums bereit.
version=210
prettyVersion=2.1.0
minRevision=0
