name=mk-nds-adt
author=Carsten Rohe
version=2.1.0
sentence=Java ADT-Klassen für das Fach Informatik in Niedersachsen.
paragraph=Diese Library stellt die ADT-Klassen BinTree, DynArray, Queue und Stack gemäß den Vorgaben des Niedersächsischen Kultusministeriums bereit.
