name=mk-nds-adt
authors=Carsten Rohe, Landesnetzwerk Informatik Niedersachsen
url=https://github.com/karlgerd/mk-nds-adt
categories=Data
sentence=ADT-Klassen für den Informatikunterricht in Niedersachsen.
paragraph=Diese Java-Bibliothek stellt BinTree, DynArray, Queue und Stack gemäß den ergänzenden Hinweisen des Niedersächsischen Kultusministeriums bereit und ist auch in Processing 4 nutzbar.
version=210
prettyVersion=2.1.0
minRevision=0
